# Generated by Django 6.1.1 on 2026-10-06 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_name", models.CharField(max_length=200)),
                (
                    "organization_type",
                    models.CharField(
                        choices=[
                            ("nonprofit", "Nonprofit"),
                            ("community", "Community Organization"),
                            ("student", "Student Organization"),
                            ("education", "Education Program"),
                            ("youth", "Youth Program"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("mission", models.TextField()),
                ("target_population", models.TextField()),
                ("contact_name", models.CharField(max_length=100)),
                ("contact_email", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
